# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        r-version: [3.5, 3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install Curl
        run: |
            sudo apt update && sudo apt install libcurl4-openssl-dev
      - name: Check
        run: |
          git clone https://github.com/MitsuhaMiyamizu/minqa.git
          Rscript test.R
          Rscript ./minqa/tests/newuoa.R
          Rscript ./minqa/tests/cyq-minqa.R
          Rscript ./minqa/tests/rvaltest.R
